### PR TITLE
A GUI configuration with Qt over ClassIn Mover

### PR DESCRIPTION
**Pull request by RayTangCha**
Well, I think it will be good to embed ClassIn Mover in a GUI application. Wouldn't it be nice?

### CODE REVIEW

**Comment by CarlGao4** [comment]
Thanks for your PR! 
In fact, I'm not using ClassIn with focused learning mode anymore, so the project has been paused...
In addition, I'm not familiar with Qt, so please help me setting up the environment and build an executable.

**Comment by CarlGao4** [comment]
By the way, I want to discuss something privately with you. Can you email me at gaoweiqicarl1@163.com?

**Comment by RayTangCha** [comment]
Actually, I'm using QtCreator to write Qt and QtCreator seems not to allow most of the functions of string (Possibly because of its own QString system). So I tried to build v1.0.3 with Dev-C++ and use WinExec() to execute ClassIn_Mover.exe. For releases, you can see https://github.com/RayTangCha/ClassIn-Mover/releases/tag/v.50-GUI. <NOTE>I wanted to add a autoclick module in order to make people's life easier, but it's too slow. So it's just like an empty shell.
By the way, Qt is BIGGGGGGGGGGGGG, so please consider that in your choices.
Also, have a look at something called ClassOut. I don't know how they did it.

**Comment by CarlGao4** [comment]
ClassOut is quite simple. Just Dutour. You can see its wiki [here](https://github.com/microsoft/Detours/wiki).

**Comment by CarlGao4** [comment]
By the way, I'm writing a GUI myself and you can see I have created a new branch called `v1.0`.

**Comment by CarlGao4** [comment]
There is no need for this PR since I've made a GUI.

**Pull request closed without merging**
